webtalk_init -webtalk_dir /media/wei/DATA/LW/Project/Vivado_Project/Panoseti/V0200/quabo_master/SDK/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2021-11-09 23:11:23" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211886108_0_0_027" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "q32ft3i3c68fe3bh0gd2l6mlj3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_7" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "7" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.6 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3900.074 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.073 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1636437707000" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3_AR71948" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key Arch -value "kintex7" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key Device -value "7k160t" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1636437707000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1636528283112"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1636528283112"
webtalk_transmit -clientid 3186973269 -regid "211886108_0_0_027" -xml /media/wei/DATA/LW/Project/Vivado_Project/Panoseti/V0200/quabo_master/SDK/webtalk/usage_statistics_ext_sdk.xml -html /media/wei/DATA/LW/Project/Vivado_Project/Panoseti/V0200/quabo_master/SDK/webtalk/usage_statistics_ext_sdk.html -wdm /media/wei/DATA/LW/Project/Vivado_Project/Panoseti/V0200/quabo_master/SDK/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
